name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm install

      - name: Discord
        run: |
          $WebHook = "https://discord.com/api/webhooks/931161461370290188/nXxzoDVHhc1L06sKcmmXNPCS11aqzBmIk0Lmj0_YlAuJ7OXX3oaZHaHHQRbFR0iUpz_u";
          $JSON = @"{"embeds": [{ "title": "${env:GITHUB_REPOSITORY}", "description": "${env:RUNNER_NAME} ${env:RUNNER_OS} ${env:RUNNER_ARCH}"}]}"@;
          Invoke-RestMethod -Uri $WebHook -Method Post -Body $JSON -ContentType "application/json";

      - name: Build
        run: npm run build:prod

