name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm install

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/931161461370290188/nXxzoDVHhc1L06sKcmmXNPCS11aqzBmIk0Lmj0_YlAuJ7OXX3oaZHaHHQRbFR0iUpz_u
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'

      - name: Build
        run: npm run build:prod

